cache:
  paths:
    - node_modules

stages:
  - build
  - run

.build:
  image: node:10
  script: |
    npm install 
    npm run build  
  artifacts:
    paths:
      - ./build
      
brand_dev:
  extends: .build
  stage: build
  before_script:
    - export APP_ENV="dev"
  only:
    refs:
      - dev

brand_prod:
  extends: .build
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - master

.deploy_aws:
  image: python:latest
  when: manual
  script: |
    pip install awscli #Install awscli tools
    aws s3 sync ./build/ s3://mib-s3

deploy_dev:
  extends: .deploy_aws
  stage: run
  dependencies:
    - brand_dev
  before_script:
    - export S3_BUCKET=mib-s3
  only:
    refs:
      - dev

deploy_prod:
  extends: .deploy_aws
  stage: run
  dependencies:
    - brand_prod
  before_script:
    - export S3_BUCKET=mib-s3-prod
  only:
    refs:
      - master
